#
# Makefile generated by gec.
#

.PHONY: all install clean distclean uninstall

all: app

prefix = /usr/local
exec_prefix = $(prefix)
bindir = $(exec_prefix)/bin
mandir = $(prefix)/man
man1dir = $(mandir)/man1

INSTALL = install -C
INSTALL_PROGRAM = $(INSTALL)
INSTALL_DATA = $(INSTALL)

CFLAGS += `/home/zhou/project/Eiffel/library/base/elks/encoding/implementation/unix/Clib/iconv-config --include_path` -I"/home/zhou/project/Eiffel/library/base/elks/encoding/implementation/include" 
LDFLAGS += `/home/zhou/project/Eiffel/library/base/elks/encoding/implementation/unix/Clib/iconv-config --library` 
LDLIBS += -lm  
OBJS = app1.o

app: $(OBJS) app.h
	$(CC) $(LDFLAGS) -o app $(OBJS) $(LDLIBS)

clean:
	-rm $(OBJS) app

distclean: clean

install:
	$(INSTALL_PROGRAM) -d $(DESTDIR)$(bindir)
	$(INSTALL_PROGRAM) app $(DESTDIR)$(bindir)

uninstall:
	-rm -f $(DESTDIR)$(bindir)/app

.c.o:
	$(CC) $(CFLAGS) -c $<
